name: on_merge

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  format:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            override: true
            toolchain: stable
            components: rustfmt, clippy
        - uses: Swatinem/rust-cache@v1
        - uses: actions-rs/cargo@v1
          with:
            command: fmt
            args: --all -- --check

  clippy:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            override: true
            toolchain: stable
            components: rustfmt, clippy
        - uses: Swatinem/rust-cache@v1
        - uses: actions-rs/cargo@v1
          with:
            command: clippy
            args: -- -D warnings

  build:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            override: true
            toolchain: stable
            components: rustfmt, clippy
        - uses: Swatinem/rust-cache@v1
        - uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --verbose
  test:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            override: true
            toolchain: stable
            components: rustfmt, clippy
        - uses: Swatinem/rust-cache@v1
        - uses: actions-rs/cargo@v1
          with:
            command: test
            args: --release --verbose --all-features

  doc:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            override: true
            toolchain: stable
            components: rustfmt, clippy
        - uses: Swatinem/rust-cache@v1
        - run: cargo doc
